### ISSUE TITLE
Quản lý thể loại sách - Thêm , Xoá , Sửa

### ISSUE THREAD

**Issue by duyan0** [duyan0/QUANLYNHASACH#13]

**Comment by 23thyu** [comment]
Thêm các thông báo khi thêm , xóa , sửa của  Quản lý thể loại 
Khi xóa thể loại  mà còn dữ liệu web không thông báo mà web hiện bị lỗi ( chết web ).
Khi Sửa và Thêm mà thiếu các trường của thể loại mà còn dữ liệu web không thông báo mà web hiện bị lỗi ( chết web ).
