### ISSUE TITLE
Quản lý nhà xuất bản - Thêm , Xoá , Sửa

### ISSUE THREAD

**Issue by duyan0** [duyan0/QUANLYNHASACH#15]

**Comment by 23thyu** [comment]
Thêm các thông báo khi thêm , xóa , sửa của  Quản lý nhà xuất bản 
Khi xóa nhà xuất bản mà còn dữ liệu web không thông báo mà web hiện bị lỗi ( chết web ).
Khi Sửa và Thêm mà thiếu các trường nhà xuất bản mà còn dữ liệu web không thông báo mà web hiện bị lỗi ( chết web ).
