### ISSUE TITLE
Quản lý tài khoản khách hàng - Thêm , Xoá , Sửa

### ISSUE THREAD

**Issue by duyan0** [duyan0/QUANLYNHASACH#16]

**Comment by 23thyu** [comment]
Thêm các thông báo khi thêm , xóa , sửa của Quản lý tài khoản
Khi xóa tài khoản mà còn dữ liệu web không thông báo mà web hiện bị lỗi ( chết web ).
Khi Sửa và Thêm mà thiếu các trường của tài khoản mà còn dữ liệu web không thông báo mà web hiện bị lỗi ( chết web ).

**Comment by duyan0** [comment]
Bug - Không cập nhật thông tin khách hàng được
